[package]
name = "rust-minecraft"
version = "0.1.0"
edition = "2021"
authors = ["xd Abi"]
repository = "https://github.com/xd-Abi/rust-minecraft"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
